database: gh_so
user: postgres
host: localhost
port: 5432
password: yourpasswordhere
train_size: 25000 # number of train data samples
test_size: 5000 # number of test data samples
features: [
        'dates',
        'desc_aboutme',
        'desc_comment',
        # 'desc_pbody',
        # 'desc_ptitle',
        'locations',
        'tags',
        'user_names'
    ]
models: ["rf", "gbdt", "knn", "lg"]
rerun: True # if true, all data is deleted and regenerated
doCharts: True  # if true, we generate charts after prediction